version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    env_file:
      - .env
    command: gunicorn -w 12 wsgi:application -b 0.0.0.0:${PORT} --limit-request-line 0
    networks:
      - ibl-chatbot
      - traefik-proxy
    ports:
      - "${PORT}:${PORT}"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-proxy"
      ## HTTP
      - "traefik.http.routers.${TRAEFIK_APP_ID}.entrypoints=web"
      - "traefik.http.routers.${TRAEFIK_APP_ID}.rule=Host(`${HOST}`)"
      - "traefik.http.routers.${TRAEFIK_APP_ID}.service=${TRAEFIK_APP_ID}-secure"
      - "traefik.http.services.${TRAEFIK_APP_ID}.loadbalancer.server.port=${PORT}"

      # Redirect
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${TRAEFIK_APP_ID}.middlewares=https-redirect"

      ## HTTPS
      - "traefik.http.routers.${TRAEFIK_APP_ID}-secure.entrypoints=websecure"
      - "traefik.http.routers.${TRAEFIK_APP_ID}-secure.rule=Host(`${HOST}`)"
      - "traefik.http.routers.${TRAEFIK_APP_ID}-secure.tls=${HTTPS_ROUTER_TLS_MODE}"
      - "traefik.http.routers.${TRAEFIK_APP_ID}-secure.tls.certresolver=default"
      - "traefik.http.routers.${TRAEFIK_APP_ID}-secure.service=${TRAEFIK_APP_ID}-secure"
      - "traefik.http.services.${TRAEFIK_APP_ID}-secure.loadbalancer.server.port=${PORT}"

networks:
  ibl-chatbot:
    driver: bridge
  traefik-proxy:
    external: true